version: '3.3'

services: 
    wordpress:
        image: wordpress
        restart: always
        ports: 
            - 8080:80
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
            - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./src:/var/www/html

    db:
        image: mariadb
        restart: always
        environment: 
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: cd
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes: 
            - db:/var/lib/mysql

    phpmyadmin:
        depends_on: 
            - db
        image: phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            - PMA_ARBITRARY=1
        
volumes: 
    db:
